#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift(File.join(__dir__, 'lib'))
$LOAD_PATH.unshift(File.join(__dir__, 'vendor', 'puppet-lint', 'lib'))
Dir[File.join(__dir__, 'vendor', 'puppet-lint-*', 'lib')].sort.each { |path| $LOAD_PATH.unshift(path) }
$LOAD_PATH.unshift(File.join(__dir__, 'vendor', 'molinillo', 'lib'))
$LOAD_PATH.unshift(File.join(__dir__, 'vendor', 'puppetfile-resolver', 'lib'))

require 'puppet_languageserver'

options = PuppetLanguageServer::CommandLineParser.parse(ARGV)
PuppetLanguageServer.init_puppet(options)
PuppetLanguageServer.rpc_server(options)
