#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift(File.join(__dir__, 'lib'))
$LOAD_PATH.unshift(File.join(__dir__, 'vendor', 'hiera-eyaml', 'lib'))
$LOAD_PATH.unshift(File.join(__dir__, 'vendor', 'openvox-strings', 'lib'))
$LOAD_PATH.unshift(File.join(__dir__, 'vendor', 'rgen', 'lib'))
$LOAD_PATH.unshift(File.join(__dir__, 'vendor', 'yard', 'lib'))

require 'puppet_languageserver_sidecar'

options = PuppetLanguageServerSidecar::CommandLineParser.parse(ARGV)
PuppetLanguageServerSidecar.init_puppet_sidecar(options)
PuppetLanguageServerSidecar.execute_and_output(options)
